### PR TITLE
Cleaned up the script parsing code a bit

### PR DESCRIPTION
**Pull request by rtfoley**

### CODE REVIEW

**Comment by rtfoley** [comment]
@BenBernardCIS and @Julian-B: I added some comments and cleaned up some of the formatting a bit. I'm going to try leveraging regular expressions within the parsing code, and add some unit testing (in my fork). The unit testing can help ensure that the parser logic doesn't have any bugs, and minimize risk.

**Comment by BenBernardCIS** [comment]
Sounds good. We fixed a couple of parsing bugs today and got it up and running on the RoboRio.  It’s pretty cool to see!  Of course all we could actually check was that the controlled lights blinked as expected.

We will commit that in the morning.

**Comment by rtfoley** [comment]
Awesome!

Can you commit some of the script files as well? That will help with the
unit tests.

**Comment by Julian-B** [comment]
Newest version is on my repo!
Im not sure how to only merge the most recent commit, and the others conflict.

**Comment by BenBernardCIS** [comment]
The script files are on the drive computer, but here’s an off-the-cuff example:

# Any blank line or line starting with a # is a comment

drive forward 24 inches at .5 speed

turn right 90 degrees

drive forward 12 inces

turn left 90 degrees

wait 5 seconds

move stacker to ground

drive forward 10 inches at .5 speed

move stacker to CLEAR_FIRST

drive backward 12 inches 

# note that all commands accept abbreviated variants assuming reasonable defaults for omitted values

wait 500

#is equivalent to

wait 500 milliseconds

wait .5 seconds

# while:

drive forward 12

# is the same as

drive forward 12 inches at .6 speed

# Parse errors should show up in the drivestation log

# We are working on adding full parse details to the log as well

**Pull request merged**
